/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./../routes/__root"
import { Route as SidebarRouteImport } from "./../routes/_sidebar"
import { Route as SidebarIndexRouteImport } from "./../routes/_sidebar/index"
import { Route as SidebarPreferencesRouteImport } from "./../routes/_sidebar/preferences"
import { Route as SidebarCatalogRouteImport } from "./../routes/_sidebar/catalog"
import { Route as SidebarAdminRouteImport } from "./../routes/_sidebar/admin"
import { Route as SidebarChatIndexRouteImport } from "./../routes/_sidebar/chat.index"
import { Route as SidebarCatalogIndexRouteImport } from "./../routes/_sidebar/catalog.index"
import { Route as SidebarChatNewRouteImport } from "./../routes/_sidebar/chat.new"
import { Route as SidebarChatConversationIdRouteImport } from "./../routes/_sidebar/chat.$conversationId"
import { Route as SidebarCatalogAgentIdRouteImport } from "./../routes/_sidebar/catalog.$agentId"
import { Route as SidebarAdminSettingsRouteImport } from "./../routes/_sidebar/admin.settings"
import { Route as SidebarAdminCatalogRouteImport } from "./../routes/_sidebar/admin.catalog"

const SidebarRoute = SidebarRouteImport.update({
  id: "/_sidebar",
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarIndexRoute = SidebarIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarPreferencesRoute = SidebarPreferencesRouteImport.update({
  id: "/preferences",
  path: "/preferences",
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarCatalogRoute = SidebarCatalogRouteImport.update({
  id: "/catalog",
  path: "/catalog",
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarAdminRoute = SidebarAdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarChatIndexRoute = SidebarChatIndexRouteImport.update({
  id: "/chat/",
  path: "/chat/",
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarCatalogIndexRoute = SidebarCatalogIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SidebarCatalogRoute,
} as any)
const SidebarChatNewRoute = SidebarChatNewRouteImport.update({
  id: "/chat/new",
  path: "/chat/new",
  getParentRoute: () => SidebarRoute,
} as any)
const SidebarChatConversationIdRoute =
  SidebarChatConversationIdRouteImport.update({
    id: "/chat/$conversationId",
    path: "/chat/$conversationId",
    getParentRoute: () => SidebarRoute,
  } as any)
const SidebarCatalogAgentIdRoute = SidebarCatalogAgentIdRouteImport.update({
  id: "/$agentId",
  path: "/$agentId",
  getParentRoute: () => SidebarCatalogRoute,
} as any)
const SidebarAdminSettingsRoute = SidebarAdminSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => SidebarAdminRoute,
} as any)
const SidebarAdminCatalogRoute = SidebarAdminCatalogRouteImport.update({
  id: "/catalog",
  path: "/catalog",
  getParentRoute: () => SidebarAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof SidebarIndexRoute
  "/admin": typeof SidebarAdminRouteWithChildren
  "/catalog": typeof SidebarCatalogRouteWithChildren
  "/preferences": typeof SidebarPreferencesRoute
  "/admin/catalog": typeof SidebarAdminCatalogRoute
  "/admin/settings": typeof SidebarAdminSettingsRoute
  "/catalog/$agentId": typeof SidebarCatalogAgentIdRoute
  "/chat/$conversationId": typeof SidebarChatConversationIdRoute
  "/chat/new": typeof SidebarChatNewRoute
  "/catalog/": typeof SidebarCatalogIndexRoute
  "/chat/": typeof SidebarChatIndexRoute
}
export interface FileRoutesByTo {
  "/admin": typeof SidebarAdminRouteWithChildren
  "/preferences": typeof SidebarPreferencesRoute
  "/": typeof SidebarIndexRoute
  "/admin/catalog": typeof SidebarAdminCatalogRoute
  "/admin/settings": typeof SidebarAdminSettingsRoute
  "/catalog/$agentId": typeof SidebarCatalogAgentIdRoute
  "/chat/$conversationId": typeof SidebarChatConversationIdRoute
  "/chat/new": typeof SidebarChatNewRoute
  "/catalog": typeof SidebarCatalogIndexRoute
  "/chat": typeof SidebarChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_sidebar": typeof SidebarRouteWithChildren
  "/_sidebar/admin": typeof SidebarAdminRouteWithChildren
  "/_sidebar/catalog": typeof SidebarCatalogRouteWithChildren
  "/_sidebar/preferences": typeof SidebarPreferencesRoute
  "/_sidebar/": typeof SidebarIndexRoute
  "/_sidebar/admin/catalog": typeof SidebarAdminCatalogRoute
  "/_sidebar/admin/settings": typeof SidebarAdminSettingsRoute
  "/_sidebar/catalog/$agentId": typeof SidebarCatalogAgentIdRoute
  "/_sidebar/chat/$conversationId": typeof SidebarChatConversationIdRoute
  "/_sidebar/chat/new": typeof SidebarChatNewRoute
  "/_sidebar/catalog/": typeof SidebarCatalogIndexRoute
  "/_sidebar/chat/": typeof SidebarChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/admin"
    | "/catalog"
    | "/preferences"
    | "/admin/catalog"
    | "/admin/settings"
    | "/catalog/$agentId"
    | "/chat/$conversationId"
    | "/chat/new"
    | "/catalog/"
    | "/chat/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/admin"
    | "/preferences"
    | "/"
    | "/admin/catalog"
    | "/admin/settings"
    | "/catalog/$agentId"
    | "/chat/$conversationId"
    | "/chat/new"
    | "/catalog"
    | "/chat"
  id:
    | "__root__"
    | "/_sidebar"
    | "/_sidebar/admin"
    | "/_sidebar/catalog"
    | "/_sidebar/preferences"
    | "/_sidebar/"
    | "/_sidebar/admin/catalog"
    | "/_sidebar/admin/settings"
    | "/_sidebar/catalog/$agentId"
    | "/_sidebar/chat/$conversationId"
    | "/_sidebar/chat/new"
    | "/_sidebar/catalog/"
    | "/_sidebar/chat/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SidebarRoute: typeof SidebarRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_sidebar": {
      id: "/_sidebar"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof SidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_sidebar/": {
      id: "/_sidebar/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof SidebarIndexRouteImport
      parentRoute: typeof SidebarRoute
    }
    "/_sidebar/preferences": {
      id: "/_sidebar/preferences"
      path: "/preferences"
      fullPath: "/preferences"
      preLoaderRoute: typeof SidebarPreferencesRouteImport
      parentRoute: typeof SidebarRoute
    }
    "/_sidebar/catalog": {
      id: "/_sidebar/catalog"
      path: "/catalog"
      fullPath: "/catalog"
      preLoaderRoute: typeof SidebarCatalogRouteImport
      parentRoute: typeof SidebarRoute
    }
    "/_sidebar/admin": {
      id: "/_sidebar/admin"
      path: "/admin"
      fullPath: "/admin"
      preLoaderRoute: typeof SidebarAdminRouteImport
      parentRoute: typeof SidebarRoute
    }
    "/_sidebar/chat/": {
      id: "/_sidebar/chat/"
      path: "/chat"
      fullPath: "/chat/"
      preLoaderRoute: typeof SidebarChatIndexRouteImport
      parentRoute: typeof SidebarRoute
    }
    "/_sidebar/catalog/": {
      id: "/_sidebar/catalog/"
      path: "/"
      fullPath: "/catalog/"
      preLoaderRoute: typeof SidebarCatalogIndexRouteImport
      parentRoute: typeof SidebarCatalogRoute
    }
    "/_sidebar/chat/new": {
      id: "/_sidebar/chat/new"
      path: "/chat/new"
      fullPath: "/chat/new"
      preLoaderRoute: typeof SidebarChatNewRouteImport
      parentRoute: typeof SidebarRoute
    }
    "/_sidebar/chat/$conversationId": {
      id: "/_sidebar/chat/$conversationId"
      path: "/chat/$conversationId"
      fullPath: "/chat/$conversationId"
      preLoaderRoute: typeof SidebarChatConversationIdRouteImport
      parentRoute: typeof SidebarRoute
    }
    "/_sidebar/catalog/$agentId": {
      id: "/_sidebar/catalog/$agentId"
      path: "/$agentId"
      fullPath: "/catalog/$agentId"
      preLoaderRoute: typeof SidebarCatalogAgentIdRouteImport
      parentRoute: typeof SidebarCatalogRoute
    }
    "/_sidebar/admin/settings": {
      id: "/_sidebar/admin/settings"
      path: "/settings"
      fullPath: "/admin/settings"
      preLoaderRoute: typeof SidebarAdminSettingsRouteImport
      parentRoute: typeof SidebarAdminRoute
    }
    "/_sidebar/admin/catalog": {
      id: "/_sidebar/admin/catalog"
      path: "/catalog"
      fullPath: "/admin/catalog"
      preLoaderRoute: typeof SidebarAdminCatalogRouteImport
      parentRoute: typeof SidebarAdminRoute
    }
  }
}

interface SidebarAdminRouteChildren {
  SidebarAdminCatalogRoute: typeof SidebarAdminCatalogRoute
  SidebarAdminSettingsRoute: typeof SidebarAdminSettingsRoute
}

const SidebarAdminRouteChildren: SidebarAdminRouteChildren = {
  SidebarAdminCatalogRoute: SidebarAdminCatalogRoute,
  SidebarAdminSettingsRoute: SidebarAdminSettingsRoute,
}

const SidebarAdminRouteWithChildren = SidebarAdminRoute._addFileChildren(
  SidebarAdminRouteChildren,
)

interface SidebarCatalogRouteChildren {
  SidebarCatalogAgentIdRoute: typeof SidebarCatalogAgentIdRoute
  SidebarCatalogIndexRoute: typeof SidebarCatalogIndexRoute
}

const SidebarCatalogRouteChildren: SidebarCatalogRouteChildren = {
  SidebarCatalogAgentIdRoute: SidebarCatalogAgentIdRoute,
  SidebarCatalogIndexRoute: SidebarCatalogIndexRoute,
}

const SidebarCatalogRouteWithChildren = SidebarCatalogRoute._addFileChildren(
  SidebarCatalogRouteChildren,
)

interface SidebarRouteChildren {
  SidebarAdminRoute: typeof SidebarAdminRouteWithChildren
  SidebarCatalogRoute: typeof SidebarCatalogRouteWithChildren
  SidebarPreferencesRoute: typeof SidebarPreferencesRoute
  SidebarIndexRoute: typeof SidebarIndexRoute
  SidebarChatConversationIdRoute: typeof SidebarChatConversationIdRoute
  SidebarChatNewRoute: typeof SidebarChatNewRoute
  SidebarChatIndexRoute: typeof SidebarChatIndexRoute
}

const SidebarRouteChildren: SidebarRouteChildren = {
  SidebarAdminRoute: SidebarAdminRouteWithChildren,
  SidebarCatalogRoute: SidebarCatalogRouteWithChildren,
  SidebarPreferencesRoute: SidebarPreferencesRoute,
  SidebarIndexRoute: SidebarIndexRoute,
  SidebarChatConversationIdRoute: SidebarChatConversationIdRoute,
  SidebarChatNewRoute: SidebarChatNewRoute,
  SidebarChatIndexRoute: SidebarChatIndexRoute,
}

const SidebarRouteWithChildren =
  SidebarRoute._addFileChildren(SidebarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SidebarRoute: SidebarRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
